[project]
name = "did-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.2.1",
    "bitsandbytes>=0.45.0",
    "datasets>=3.2.0",
    "langchain>=1.2.7",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.7",
    "neo4j>=6.1.0",
    "ollama>=0.6.1",
    "peft>=0.14.0",
    "pytest>=9.0.2",
    "ray>=2.53.0",
    "torch>=2.0.0",
    "tqdm>=4.67.1",
    "transformers>=4.48.0",
    "tree-sitter>=0.25.2",
    "tree-sitter-python>=0.25.0",
    "tree-sitter-rust>=0.24.0",
    "vllm>=0.14.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
